### ISSUE TITLE
No league details in tab[BUG]

### ISSUE THREAD

**Issue by cheilson** [ho-dev/HattrickOrganizer#1455]
**Describe the bug**
League tab is empty, can't get the league to show.

**To Reproduce**
1. Go to 'LEAGUE tab'

**Screenshots**
[https://ibb.co/2yhq97D](url)

**Platform information:**
 - Win 11 home, 21H2
 - HO 6.0 DEV (r270)

**Additional context**

**Comment by wsbrenk** [comment]
@cheilson this seems to be a problem after the very first download. Did it remain when you download again (F11)?

**Comment by cheilson** [comment]
Yes, it persists. I tried checking and unchecking everything at download window.

**Comment by cheilson** [comment]
And now the league tab is full. Funny, I did nothing different.

**Comment by masterpatje** [comment]
> @cheilson this seems to be a problem after the very first download. Did it remain when you download again (F11)?

@wsbrenk you fixed it on the very first download. It had to do with no matches yet present in the off-season. As soon as the first match of the league is played everything works perfectly also on the very first download.

Suggestion was to see if League Details (teams) can be subtracted from .hrf file from league ID (if available?), so that even when no matches are played the League Table can be shown as soon as the new league (and league teams are visible in hattrick).

But I think you already answered that one, that information is not available in .hrf to subtract that League data and that the data for the league is substracted from the matches. But correct me if I am wrong.

**Comment by wsbrenk** [comment]
that's right - just looked if there is a chance to do it the way @masterpatje suggests, but  unfortunately ht (chpp) provides the information of the participating teams only when the games are fixed. So there are some weeks at the beginning of a new season without any information about the teams in the league.
