### ISSUE TITLE
[BUG] Issue with Hattrick Organizer Installer process on macOS

### ISSUE THREAD

**Issue by MaxiGalaxi** [ho-dev/HattrickOrganizer#1849]
**Describe the bug**
I can't update nor can I reinstall HO.

**To Reproduce**
I'll download the JRE version either manually or via the updater in HO. Then I'll start the updater, this seems to open up a process called "Hattrick Organizer Installer" but I can't view the application/windows thus I am not able to navigate through the update process.

**Platform information:**
 - OS: macOS
 - Version 13.3
 - HO 5.2

**Additional context**
I have been the issue for quite a while ;)

**Comment by wsbrenk** [comment]
@tychobrailleur you are the mac expert, i remember. do you have any idea?

**Comment by sergei-cl** [comment]
Same problem here 😞

**Comment by wsbrenk** [comment]
@tychobrailleur you are the mac expert - could you try to fix this?

**Comment by sergei-cl** [comment]
> @tychobrailleur you are the mac expert - could you try to fix this?

I'm available for any kind of feedback or testing if needed @tychobrailleur

**Comment by sergei-cl** [comment]
7.2 still have the same installer problem on MacOS :(

**Comment by wsbrenk** [comment]
@sergei-cl sorry - but i'm not an mac expert. maybe this video can help? [(https://www.youtube.com/watch?v=GUDrWcNi9pA)](https://www.youtube.com/watch?v=GUDrWcNi9pA)

**Comment by sergei-cl** [comment]
Thanks @wsbrenk unfortunately this video doesn't help at all. The installer just get stucked after opening this:
![CleanShot 2023-07-24 at 12 30 21@2x](https://github.com/akasolace/HO/assets/137583149/922f6b79-83b7-4af4-a58a-1b0b4ce95d63)
Then it simply dissappears and nothing happens even being open.

**Comment by wsbrenk** [comment]
@sergei-cl could you check if there are install4j log files in the subdirectory .install4j of your installation directory. in my case (windows) there are
* installation.log
* uninstallPrevious.log

Please check if there are hints or better upload them to this thread.

**Comment by sergei-cl** [comment]
@wsbrenk I've try to find those files but don't know how to locate it on my Mac 😢
> @sergei-cl could you check if there are install4j log files in the subdirectory .install4j of your installation directory. in my case (windows) there are
> 
> * installation.log
> * uninstallPrevious.log
> 
> Please check if there are hints or better upload them to this thread.

**Comment by kempsu** [comment]
> 

Can confirm. This needs to be fixed :/
I am happy to help, so I will see if I can find any log files

**Comment by kempsu** [comment]
Here's a log file I was able to obtain:

[i4j_log_HO_11756506834732886662.log](https://github.com/akasolace/HO/files/12206721/i4j_log_HO_11756506834732886662.log)

**Comment by sergei-cl** [comment]
> > Then it simply dissappears and nothing happens even being open.
> 
> Can confirm. This needs to be fixed :/ I am happy to help, so I will see if I can find any log files

**Comment by kempsu** [comment]
1. Open Terminal app on your Mac
2. Type: open $TMPDIR

**Comment by sergei-cl** [comment]
Here is my log too:
[i4j_log_HO_2659267347727084719.log](https://github.com/akasolace/HO/files/12207776/i4j_log_HO_2659267347727084719.log)

**Comment by madcooper82** [comment]
Still the same here. Her is my log of the same issue: 
[i4j_log_HO_1819841152434609014.log](https://github.com/akasolace/HO/files/12267107/i4j_log_HO_1819841152434609014.log)

**Comment by sergei-cl** [comment]
@tychobrailleur @wsbrenk any clue of a possible solution?? 🙏🏻

**Comment by tychobrailleur** [comment]
Hi folks, sorry, I have been on and off the project, busy with real life...  I no longer have a Mac so cannot test right now.

At first glance, it seems to be some issue with the install4j installer, it seems to be hanging at the same place:

```
[INFO] com.install4j.runtime.beans.screens.StartupScreen [ID 1]: command: move 1 screens, executing actions, checking condition
[INFO] com.install4j.runtime.beans.screens.WelcomeScreen [ID 2]: Show screen
[INFO] Using communication backend com.install4j.runtime.installer.platform.unix.PipeCommunicationBackend
```

which seems to be around the time where the installer asks for Admin permission to install java.  It doesn't seem to be an architecture issue, because it seems to happen on both aarch64 (I assume M1) and x86_64 (I presume Intel).  

I'll do some research to see if this is a known issue, but in the meantime, some questions:

1. Which dmg does it happen with, with or without JRE?  Or both?
2. Any possibility that the prompt window is somewhat hidden, for example behind another window?   Or on a separate monitor? 

![admin](https://github.com/akasolace/HO/assets/114285/689576b2-7cd8-4c37-ba5c-29a09c916c73)

3. Any antivirus that might block this permission request?  We don't sign our packages, so this might cause some troubles with them
4. Anything interesting in the install4j logs?  It'd be nice if someone with the issue could do the following:
- Extract the installer from the dmg
- Open a terminal window, and `cd` into the directory where the installer is extracted
- Execute:

```
INSTALL4J_LOG=yes Hattrick\ Organizer\ Installer.app/Contents/MacOS/JavaApplicationStub
```

For people who are completely stuck, you can still use the portable version of HO:

1. Install [Java 17](https://adoptium.net/temurin/releases/) on your system
2. Download the [portable version of HO](https://github.com/akasolace/HO/releases/download/7.2/HO-7.2.510.2-portable-unix.tar.gz)
3. Create a new directory somewhere on your system, for example called “Hattrick”
4. Extract the content of the downloaded portable package (`HO-7.2.510.2-portable-unix.tar.gz`) into that new folder – it should work by right-clicking, Open With, Archive Utility
5. Execute the `HO` file in the folder

**Comment by sergei-cl** [comment]
Hi @tychobrailleur ,
Great to ear from you !!
About your questions:

_1. Which dmg does it happen with, with or without JRE? Or both?_
Both.
_2. Any possibility that the prompt window is somewhat hidden, for example behind another window? Or on a separate monitor?_
No, I've checked it more than once.
_3. Any antivirus that might block this permission request? We don't sign our packages, so this might cause some troubles with them_
Not in my case.
_4. Anything interesting in the install4j logs? It'd be nice if someone with the issue could do the following:_
Here the log. 
[ho_installer.log](https://github.com/akasolace/HO/files/12363321/ho_installer.log)

About using the portable version, I've followed the step by step and I get stuck too in a HOLauncher process but it shows nothing. HO 6.1 still works fine.

**Comment by tychobrailleur** [comment]
> About using the portable version, I've followed the step by step and I get stuck too in a HOLauncher process but it shows nothing. HO 6.1 still works fine.

Interesting.  I don't think this is related, but this mean you already have an existing installation of HO working.  Do you have logs for that hanging portable version startup?  I suspect here this could be related to database migrations.  This could potentially be validated by moving the existing HO files:

```
mv ~/Library/Application\ Support/{HO,HO.bak}
```

and restarting.

So far I haven't found anything on that issue mentioned anywhere.  There is mention in the install4j changelog of a potential hanging when using dark mode: https://www.ej-technologies.com/download/install4j/changelog.html fixed in release 10.0.3 – in any case, we probably need to update the version of the installer, or find an alternative solution.  I'll see if I can look into that at the weekend.

**Comment by sergei-cl** [comment]
Hi @tychobrailleur !
I've moved the HO files and tried 2 things:

1. Installing the latest version of HO installer. - Doesn't work.
2. Run the portable version of the latest stable version. - Works but a lot of stuff seems quite buggy and slow.

Hope it helps.

**Comment by wsbrenk** [comment]
@tychobrailleur  changing the /opt sub dir of install4j is not sufficiant: 

~~~
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':media'.
> Process 'command '/bin/sh'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 1m 57s
> Task :media FAILED
Updated licensing information.
install4j version 10.0.6 (build 10097), built on 2023-06-19
Your license key is only valid for a previous major release of install4j. Please run the install4j GUI to enter a valid license key.
~~~

**Comment by wsbrenk** [comment]
i just asked for a new license key

**Comment by wsbrenk** [comment]
@tychobrailleur i don't see the `settings` option (anymore) in this repository. I'm not sure if i installed the install4j license two years ago or if @akasolace did it. 

Maybe we should do the move of this repo to the new place now to handle such things.

**Comment by tychobrailleur** [comment]
> @tychobrailleur
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':media'.
> > Executable /opt/install4j9/bin/install4jc does not exist
> ```

Ah yes – sorry, that's the kind of things that cannot be tested before it's actually merged :-)

**Comment by tychobrailleur** [comment]
> i just asked for a new license key

It looks like we need a new license for that new major version all right.  I think this is set as a env var, so moving to the new repo at this stage may indeed be a good idea.

**Comment by wsbrenk** [comment]
information from german question forum:

_I currently like to use my stable version of the HO in version 6.0 on my MacBool Pro with Ventura 13.5.1
Every now and then the curious finger twitches to update to version 7.2. ==> The download starts ==> the first queries are normal and then the installation hangs. Nothing is happening anymore.
..._

_It's the same with me. After loading the installation file, you will be asked for the password. Afterwards nothing happens anymore and if I want to turn off the MacBook, I have to kill the "Hattrick Organizer Installer" because it interrupts the shutdown ..._

**Comment by wsbrenk** [comment]
@tychobrailleur new dev version is successfully build

i replaced the install4j license key
and all urls pointing to the old repository

**Comment by sergei-cl** [comment]
@wsbrenk @tychobrailleur I've downloaded the dev version and install HO without any kind of issue 👍

**Comment by tychobrailleur** [comment]
> @wsbrenk @tychobrailleur I've downloaded the dev version and install HO without any kind of issue 👍

That's great news!  Credit where credit is due, it's all thanks to @wsbrenk !

**Comment by sergei-cl** [comment]
Hope we can see it solve soon on the stable version !

**Comment by sergei-cl** [comment]
Works fine on the latest 7.3 beta version !

**Comment by madcooper82** [comment]
Can confirm this too. Works with Beta now for me. Thanks a lot for all your efforts.
