### ISSUE TITLE
Error when trying to authorise account in new version

### ISSUE THREAD

**Issue by KenniZz** [ho-dev/HattrickOrganizer#1939]
I was still using using version 1.4 which for some reason broke down on me earlier this week.
When searching for installation files to install it again I found that there were much newer versions...
Installed version 7.3 but am unable to authorize my account.
Installed several different versions of Java and HO. 32bit, 64bit, with JRE, without, exe or zip file. All end up with the same error when trying to download and authorize for the first time.

![image](https://github.com/ho-dev/HattrickOrganizer/assets/150442482/20fec2cd-4c1b-4546-ab5a-ca0d9fa78e14)
![image](https://github.com/ho-dev/HattrickOrganizer/assets/150442482/2ad3426d-3498-4ac7-b17d-3318b6eebd29)

Output log file:
 [Info]    HO: VERSION: 7.3   versionType:  RELEASE   RevisionNumber: 523
 [Info]    HOZip: Create Backup: C:\Users\kennisr\AppData\Roaming\HO\db\db_user-2023-11-10.zip
 [Debug]   DBUpdater: No DB update necessary.
 [Info]    DBManager: instance jdbc:hsqldb:file:C:\Users\kennisr\AppData\Roaming\HO\db/database; parent folder: C:\Users\kennisr\AppData\Roaming/HO
 [Info]    HOVerwaltung: language used for interface is: Nederlands
 [Info]    HOMainFrame: This is HO! version 7.3, have fun!
 [Info]    HOMainFrame: Operating system found: Windows 11 on amd64 (10.0)
 [Info]    HOMainFrame: Using java: 17.0.3 (Eclipse Adoptium)
 [Debug]   FileLoader: File will not be searched anymore: /prediction\predictionTypes.conf
 [Warning] Lineup: no match to determine location
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Error]   OAuthDialog: Exception in obtainUserCode: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called

**Comment by masterpatje** [comment]
I know that the developers once said that you can't upgrade directly from the 1.4 version, because the database will not be recognised.

If I am correct there is only one work around available but it is quite tricky and might fail. You can try to search for closed issues to get the information how it can be done, but I think that you needed to first upgrade from 1.4 tot 4. I know that between version 6 and 7 also changes were made in database (I believe that this was the case) but don't know if you can directly upgrade from 4 to 7 or with a step between.

Alternative (what I did) is starting with a new download and then import all old HRF files in one go or in steps. But also here you have to do something, because before downloading the HRF I would advise you to a 2nd download with old league information (one of the options when downloading HRF in the application itself). And after you finished this step then import HRF. I was able to import files that were very old.

**Comment by wsbrenk** [comment]
![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/94106a69-3158-450c-928f-c1cf5029868c)

**Comment by KenniZz** [comment]
The url field is empty (see above screenshot).
I also just now tried to install version 4 but that doesn't even startup after installation

**Comment by wsbrenk** [comment]
@KenniZz Do you start with an empty (not existing) database? Or  were there (old) database files in  the folder C:\Users\kennisr\AppData\Roaming\HO\db ?

Please make a backup of that directory and than delete the existing database files and restart again. If that should work, you've got an corrupted database (if you have an existing backup of your old V1.4, we could try to migrate it correctly).
If that does not work, I have to investigate the authorization part of HO - I was not active in that part of the code until today...

**Comment by KenniZz** [comment]
I renamed the C:\Users\kennisr\AppData\Roaming\HO forlder
Then started HO 7.3 again
This create a new C:\Users\kennisr\AppData\Roaming\HO folder
But get the same error :(
![image](https://github.com/ho-dev/HattrickOrganizer/assets/150442482/e80058ad-720e-4156-8517-3d0729bd157d)

**Comment by wsbrenk** [comment]
https://github.com/ho-dev/HattrickOrganizer/discussions/1875#discussioncomment-6207691

**Comment by KenniZz** [comment]
could be but I don't understand what the solution means
in and outbound rules?

**Comment by wsbrenk** [comment]
these are firewall rules. did you restrict network access of some of your appllications, e. g java.exe?

But sorry - i'm no network expert.

**Comment by KenniZz** [comment]
Bingo!
Turning off the VPN on my (work) laptop did the trick. This is constantly turned on so I never thought about that.
