### ISSUE TITLE
[BUG] hrf import causes problems in training and sub-skills

### ISSUE THREAD

**Issue by johari75** [ho-dev/HattrickOrganizer#2028]
**Describe the bug**
After importing historical hrf files there are double entries in historical trainings of training tab. 
Additionally (maybe caused by the double entries) all player sub-skills are lost.

**To Reproduce**
1. New download of "HO-8.0.589.0-portable-win-DEV-JRE.zip"
2. Unzip and execute
3. First download of currrent team data from hattrick.org
4. Import last hrf from previos week.
5. error: double entries for last week
6. error: loosing all sub-skills for players in training prediction as well as in player overview

**Screenshots**
![Training](https://github.com/ho-dev/HattrickOrganizer/assets/67096604/4f56ce0e-23b2-4026-bfbe-fc08f3d61292)
![Training_sub-skills](https://github.com/ho-dev/HattrickOrganizer/assets/67096604/eb85c5b7-f8ec-41fe-8043-320d1c0df747)
![PlayerOverview_sub_skills](https://github.com/ho-dev/HattrickOrganizer/assets/67096604/87189315-a52a-4872-892c-5148b84b6240)

**Platform information:**
 - OS: Win 10
 - Version HO 8.0 DEV [8.0.589.0]

**Additional context**
I faced the same behaviour (double entries in Training tab) in HO 7.3 whithout loosing sub-skills. But I don´t trust in sub-skill values.

**Comment by wsbrenk** [comment]
Got this error when trying to reproduce this: 

[Info]    TrainingWeekManager: Next week training date: 2024-02-29 10:30:00
 [Error]   ExceptionHandler: java.lang.NullPointerException: Cannot invoke "core.training.TrainingPoints.getTrainingDuration()" because the return value of "core.training.TrainingPerPlayer.getTrainingPair()" is null
 [Error]   ExceptionHandler: core.training.TrainingPerPlayer.calcSubskillIncrement(TrainingPerPlayer.java:104)
 [Error]   ExceptionHandler: core.model.player.Player.calcSubSkills(Player.java:2020)
 [Error]   ExceptionHandler: core.model.HOModel.calcSubskills(HOModel.java:554)
 [Error]   ExceptionHandler: core.net.DownloadDialog.startDownload(DownloadDialog.java:392)
 [Error]   ExceptionHandler: core.net.DownloadDialog.actionPerformed(DownloadDialog.java:87)
 [Error]   ExceptionHandler: java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)

**Comment by johari75** [comment]
New version works fine. No double entries nor sub-skill problems.
Great job :)
